# -*- coding: utf-8 -*-
"""probabilidade

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RwpoD_cjdCrfTlDLFCZDg5NsyXsDTOaL
"""

import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

dados = pd.read_csv('/content/drive/MyDrive/Cursos/Fatec /3°Semestre/EstatisticaAplicada/Dados/pesquisa_tratada.csv', sep=',', encoding='UTF-8')
dados.head(3)

cor_preta = dados.loc[dados.cor_favorita.isin(['preta','preto'])]
cor_preta.head()

altura1 = dados.loc[dados.altura < 1.70]
altura1.head(12)

len(dados)

len(cor_preta)

len(altura1)

# CRIANDO FUNÇÃO PROBABILIDADE
def probab (A, E):
  # A = obj de estudo, E = espaço amostral
  resultado = (A / E)*100
  print('{:.2f}'.format(resultado))

# PROBABILIDADE DE RETIRAR PREFÊRENCIA COR PRETA
probab (len(cor_preta), len(dados))

# PROBABILIDADE DE SER MENOR QUE 1.70m
probab (len(altura1), len(dados))

"""## **PROBABILIDADE** **DE NÃO OCORRER**"""

# CRIANDO FUNÇÃO PROBABILIDADE DE NÃO OCORRER UM EVENTO
def probab_nao (A, E):
  resultado = (1- (A/E))*100
  print('{:.2f}'.format(resultado))

cor_vermelho = dados.loc[dados.cor_favorita.isin(['vermelha', 'vermelho'])]
cor_vermelho.head()

# PROBABILIDADE DE NÃO RETIRAR COR FAVORITA VERMELHO
probab_nao(len(cor_vermelho), len(dados))

"""## **Probabilidade da Intersecção de dois eventos independentes**"""

# CRIANDO FUNÇÃO PROBABILIDADE DA INTERSECÇÃO DE DOIS EVENTOS INDEPENDENTES
def probab_inter(A,B, E):
  resultado = (A/E * B/E)*100
  print('{:.1f}'.format(resultado))

# PROBABILIDADE DE SORTEAR DUAS PESSOAS SENDO UMA DELAS COM A ALTURA MENOR QUE 1,70
# E A OUTRA COM COR FAVORITA PRETA COM REPOSIÇÃO.
probab_inter(len(cor_preta),len(altura1),len(dados))

"""## Probabilidade da união (AUB)"""

# FUNÇÃO
def probab_uniao(A,B,AB, E):
  resultado = (A/E + B/E - AB/E) * 100
  print('{:.2f}'.format(resultado))

#PROBABILIDADE DE SELECIONAR
probab_uniao(len(cor_preta),len(altura1),(len(cor_preta)/len(dados)*len(altura1)/len(dados)), len(dados))